obj-y += lpnu_main.o
obj-y += lpnu_mach_o.o
obj-y += lpnu_vfs_compat.o
obj-y += lpnu_kext.o

ccflags-y += -I$(src)/../linux-7.0/include
ccflags-y += -I$(src)/include
ccflags-y += -I$(src)/../xnu-xnu-11215.1.10/bsd/sys
ccflags-y += -I$(src)/../xnu-xnu-11215.1.10/osfmk